### ISSUE TITLE
[UI] Add parametter controls

### ISSUE THREAD

**Issue by carlesanton** [carlesanton/JSCombine24#6]
# Description

Add controls (have to be defined how) to be able to save frames in order to do prints. Maybe even give access to some parameters using UI.

- At minimum a “Save Frame” button
- Most advanced:
    - UI Panel with:
        - Seed control ✅
        - Save frame N (be able to set that it saves the N frame automaticaly)
            - Even repeat and save every N frames
        - Initial pixel sort steps ✅
        - sort_noise_scale ✅
        - noise_direction_change_rate ✅
        - noise_radius ❌
        - pixel_sort_iters_per_steps ✅
        - initial_cellular_automata_max_steps ✅
        - random_color_change_rate ✅

# Definition of Done

# References

**Comment by carlesanton** [comment]
# TODO

- [ ]  make seed really be the seed, don’t know why it is starting from different positions
- [x]  dont reset all parameters and everything when saving an image wtf
    - [x]  It is because i am saving them on the project folder with hot reload
- [ ]  button to re-run seed
- [ ]  create counter of “times_saves_with_current_seed” to change the image filename
- [ ]  add feature to save at frame N
- [ ]  add feature to save every N frames (optional)
    - [ ]  should be downloaded automatically without asking permission?
- [ ]  Separate each html component inside its respective file
- [ ]  inside sketch create method to add all the elements (create_toolbar) inside the div called toolbar
